version: '3.1'
services:
  mysql:
    restart: always
    image: mysql:5.6
    container_name: mysql_test
    ports:
      - 60023:3306
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: gxqxx2020
    command:
      --character-set-server=gbk
      --collation-server=gbk_chinese_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO"
    volumes:
      - ./data:/var/lib/mysql

