version: '3.7'
services:
  postgis:
    image: mdillon/postgis
    restart: always
    environment:
        POSTGRES_PASSWORD: liaoin2019
    volumes:
        - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      mynet:
        ipv4_address: '172.19.0.12'


networks:
  mynet:
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16

volumes:
    data:
      driver_opts:
        type: none
        device: /usr/tools/PostGIS/data
        o: bind