version: '3.1'
services:
  nginx:
    restart: always
    image: godfs
    container_name: godfs
    ports:
      - 80:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
      - ./www:/usr/share/nginx/html
