version: '3'
services:
  kibana:
    image: kibana:7.7.0
    container_name: kibana
    environment:
      - "elasticsearch.hosts=http://192.168.136.128:9200" #设置访问elasticsearch的地址
    volumes:
      - ./config:/usr/share/kibana/config #配置文件挂载
    ports:
      - 5601:5601



# https://blog.csdn.net/u014756339/article/details/107161425
