version: '3'
services:
  imgproxy:
    image: darthsim/imgproxy:latest                               # 原镜像`darthsim/imgproxy:latest`
    container_name: imgproxy                                        # 容器名为'minio'
    restart: always                                              # 指定容器退出后的重启策略为始终重启
    ports:
      - "9100:8080"
    environment:                                      # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      IMGPROXY_LOCAL_FILESYSTEM_ROOT: /data
    volumes:                                                     # 数据卷挂载路径设置,将本机目录映射到容器目录
      - "/usr/tools/Minio/minio/data:/data"
