version: '3'
services:
  oracle:
    image: oracleinanutshell/oracle-xe-11g:1.0.0
    container_name: oracle
    ports:
      - 1520:1521
      - 5500:8080
    environment:
      # 开启远程连接
      - ORACLE_ALLOW_REMOTE=true
      # 禁用磁盘异步IO
      - ORACLE_DISABLE_ASYNCH_IO=true
      # 启用XDB用户的默认密码:XDB
      - ORACLE_ENABLE_XDB=true

