version: '3.1'
services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx2
    ports:
      - 443:443
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/cert:/cert
      - ./logs:/var/log/nginx
      - ./www:/usr/share/nginx/html
