version: "3" #版本号
services:
  service1: #服务名称（不是容器名）
    image: ascdc/jdk8  #使用的镜像
    ports:
    - "80:80"  #暴露的端口信息和docker run -d -p 80:80 一样
    restart: "always" #重启策略，能够使服务保持始终运行，生产环境推荐使用
    container_name: wxchat #容器名称
    #挂载文件ps:如果是挂载文件必须在容器中也指定名称，推荐是挂载文件夹，下面只是做个文件挂载的案例也可以
    #挂载文件夹/root/compose_test/jdk/:/data
    volumes:
    - /root/compose_test/jdk/wxchat-0.0.1-SNAPSHOT.jar:/data/wxchat-0.0.1-SNAPSHOT.jar
    entrypoint: java -jar /data/wxchat-0.0.1-SNAPSHOT.jar #启动容器后执行的命令