version: '3'
services:
  drone-server:
    image: drone/drone:latest
    container_name: drone-server
    ports:
    - "8000:80"
    - 8843:443
    - 9000
    volumes:
    - ./drone:/var/lib/drone/
    - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
    - DRONE_GITEA_SERVER=http://192.168.3.53:3000
    - DRONE_GIT_ALWAYS_AUTH=false
    - DRONE_RUNNER_CAPACITY=2
    - DRONE_SERVER_HOST=192.168.3.53:8000
    - DRONE_SERVER_PROTO=http
    - DRONE_TLS_AUTOCERT=false
    - DRONE_DATABASE_DATASOURCE=/var/lib/drone/drone.sqlite
    - DRONE_DATABASE_DRIVER=sqlite3
    - DRONE_RPC_SECRET=ALQU2M0KdptXUdTPKcEw
    - DRONE_USER_CREATE=username:xiaoyiqaz1,admin:true
    - DRONE_LOGS_DEBUG=true
    - TZ=Asia/Shanghai

  drone-agent:
    image: drone/agent:latest
    container_name: drone-agent
    restart: always
    depends_on:
    - drone-server
    environment:
    - DRONE_RPC_PROTO=http
    - DRONE_RPC_HOST=192.168.3.53:9000
    - DRONE_RPC_SECRET=ALQU2M0KdptXUdTPKcEw
    - DRONE_RUNNER_CAPACITY=2
    - DRONE_RUNNER_NAME=192.168.3.53
    - DRONE_LOGS_DEBUG=true
    - TZ=Asia/Shanghai
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock